// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkzA81SywFZRbFmoGUMgPnTil-UciY3vA',
    appId: '1:90567993757:web:ff389da3f05400e7d46774',
    messagingSenderId: '90567993757',
    projectId: 'led-strip-controller-flutter',
    authDomain: 'led-strip-controller-flutter.firebaseapp.com',
    storageBucket: 'led-strip-controller-flutter.appspot.com',
    measurementId: 'G-B1DKQG768N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-uMpcqeHs9pJgTBEfCKxJEny-zYIBWS0',
    appId: '1:90567993757:android:d7409ca3abc12c59d46774',
    messagingSenderId: '90567993757',
    projectId: 'led-strip-controller-flutter',
    storageBucket: 'led-strip-controller-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjFyIOMMXcggvNoqA8HZprrL3mdR16vXk',
    appId: '1:90567993757:ios:22602f39426fd51dd46774',
    messagingSenderId: '90567993757',
    projectId: 'led-strip-controller-flutter',
    storageBucket: 'led-strip-controller-flutter.appspot.com',
    iosClientId: '90567993757-cop3h3p9593eqs0hhe0a6u0g45et0m4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ledStripController',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjFyIOMMXcggvNoqA8HZprrL3mdR16vXk',
    appId: '1:90567993757:ios:22602f39426fd51dd46774',
    messagingSenderId: '90567993757',
    projectId: 'led-strip-controller-flutter',
    storageBucket: 'led-strip-controller-flutter.appspot.com',
    iosClientId: '90567993757-cop3h3p9593eqs0hhe0a6u0g45et0m4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ledStripController',
  );
}
